= Workshop Katas
:toc:

== Introduction
Our katas are based or copied over from the described website.

* https://kata-log.rocks/
* https://codingdojo.org/kata/

== FizzBuzz

https://kata-log.rocks/fizz-buzz-kata[Kata Description]

* Write a program that prints one line for each number from 1 to 100
* Usually just print the number itself.
* For multiples of 3 print `Fizz` instead of the number
* For the multiples of 5 print `Buzz` instead of the number
* For numbers which are multiples of both 3 and 5 print `FizzBuzz` instead of the number

== Tennis

https://kata-log.rocks/tennis-kata[Kata Description]

=== Scoring

*Points* --
The smallest unit of measurement. Points increment from Love(0)-15-30-40-game.

*Sets* --
Sets consist of 4 points each, and is won when a player reaches 4 points with at least a 2 point advantage.

*Deuce* --
Occurs if a score of 40-40 is reached.
In order to win the game, a player must win 2 consecutive points in order to take the game.
If a player wins one point, they have advantage, but if they lose the next point, the score returns to deuce.

== Task List

https://kata-log.rocks/task-list-kata[Kata Description]

Check description for more information
